### ISSUE TITLE
Question: Using Custom Tags

### ISSUE THREAD

**Issue by IanMuirhead** [straker/livingcss#16]
Quick question regarding Custom Tags.

I'm attempting to create an accordion navigation for the sections.  Ideally the @page would be the parent level of the @section.

Any ideas or direction you could send me in?

cheers

**Comment by straker** [comment]
I don't know if you can do it without a custom template, but something like this might work:

```ejs
<ul class="nav" id="nav" role="tablist">
{{#pages}}
  <li class="nav__item">
    <a href="#{{id}}" class="nav__link">{{name}}</a>
    
    <ul class="nav inner-nav">
    {{#sections}}
      <li class="nav__item">
        <a href="#{{../id}}-{{id}}" class="nav__link">{{name}}</a>
      </li>
    {{/sections}}
    </ul>
  </li>
{{/pages}}
</ul>
```

**Comment by IanMuirhead** [comment]
I'm in the midst of integrating it into a Material Design Lite custom template - so I'm already headed down that route.  Attempting to not go too far off the functionality so I can keep up to date.

What you provided is pretty close - a couple of changes were needed.

`            <ul class="nav" id="nav" role="tablist">
            {{#pages}}
              <li class="nav__item">
                <a href="{{name}}.html#{{id}}" class="nav__link">{{name}}</a>

                <ul class="nav inner-nav">
                {{#sections}}
                  <li class="nav__item">
                    <a href="#{{../id}}-{{id}}" class="nav__link">{{name}}</a>
                  </li>
                {{/sections}}
                </ul>
              </li>
            {{/pages}}
            </ul>`

**Comment by IanMuirhead** [comment]
Working now.

`
<ul class="nav" id="nav" role="tablist">
            {{#pages}}
              <li class="nav__item">
                <a href="{{name}}.html" class="nav__link">{{name}}</a>

                <ul class="nav inner-nav">
                {{#sections}}
                  <li class="nav__item">
                    <a href="{{../name}}.html#{{id}}" class="nav__link">{{name}}</a>
                  </li>
                {{/sections}}
                </ul>
              </li>
            {{/pages}}
            </ul>
`

**Comment by IanMuirhead** [comment]
Thought I would give a final update as I ran into a couple other issues.

```
<a href="{{toLowerCase name}}.html" class="nav__link">{{name}}</a>
<a href="{{toLowerCase ../name}}.html#{{id}}" class="nav__link">{{name}}</a>
```

I needed to add the handlebar helper - toLowerCase and remove spaces and replace with '-'

In my pre-process I've added:

```
Handlebars.registerHelper('toLowerCase', function(str) {
  return str.replace(/\s+/g, '-').toLowerCase();
});
```
