### ISSUE TITLE
Overriding default styles from template

### ISSUE THREAD

**Issue by reintroducing** [straker/livingcss#17]
So I want to retain most everything in the default template except the `mainStylesheet` partial (as it resets some of my global styles which I'd rather not do). In fact, I'd argue that only what is in that partial should be namespaced with .livingcss and anything that could possibly be global not include which would make this even easier, but alas.

What is the best way to replace only this portion? I don't want all the resets that happen there but I do want the rest of the styles for the style guide portions.  The only thing I can think of is re-creating the templates directory/files in my code and ripping it out of there and pointing the template to my directory instead.  The problem with that is updates to these files will no longer cascade to me and every time I update livingcss I'd have to do the copying over to my files, rip out styles i don't need from mainStylesheet partial, etc.

What is the best way forward for this?

**Comment by straker** [comment]
You can create your own mainStylesheet partial and use it, which will override mine.

```js
livingcss('styles.css', 'dist', {
  preprocess: function(context, template, Handlebars) {
    return livingcss.utils.readFiles('path/to/my/mainStylesheet.hbs', function(data, file) {
      Handlebars.registerPartial('mainStylesheet', data);
    }
  }
});
```

I'm not sure what you're asking in the first part of your issue. Are you saying that the `html`, `body`, headings, and paragraph tag declarations also be namespaced with `livingcss` so that it won't override your examples? Because if those styles are overriding your examples that is a problem and I should fix it.

**Comment by reintroducing** [comment]
Yep, that's exactly what is happening. Because those tags are inline in the page I think they take specificity over whats in my stylesheet.  And your solution above would work but the problem is that I then lose any updates you make to mainStylesheet.hbs in the future to the namespaced classes as well so I'd have to keep that updated manually.  

I would either remove the global styles you're setting or make those a separate hbs file (without the namespaced styles, just the ones that go on global elements) so that it can be either easily removed or overwritten as well.

**Comment by straker** [comment]
I'll look into it. Thanks for bringing it up.

**Comment by reintroducing** [comment]
Just wanted to follow up and see if you had a chance to make any headway into this? Is there anything I can do to help?

**Comment by straker** [comment]
I've had some time to look into it, but haven't figured out the best way to ensure no style penetration to web components just yet.

**Comment by straker** [comment]
Alright, I think I have something. Would you mind pulling the branch `preventCascade` and testing the output to see if the template still looks correct and that the styles don't cascade the examples?

**Comment by reintroducing** [comment]
Hmm, I've been using this through gulp-livingcss so not exactly sure how to use a branch of a dependency :\

**Comment by reintroducing** [comment]
I'm going to close this since we discussed this in the thread of your branch.
