### ISSUE TITLE
.livingcss-example min-width causing block to overflow

### ISSUE THREAD

**Issue by Kamilius** [straker/livingcss#26]
`.livingcss-example` element for me is having `1100px`. I don't know where this value came from yet, but it is causing this block to overflow parent container. When I'm turning it off in dev tools, everything's perfectly fine.

Here's how it looks for me:
<img width="1092" alt="screen shot 2017-01-18 at 11 27 09 am" src="https://cloud.githubusercontent.com/assets/3115794/22060203/8aefda4e-dd78-11e6-969e-f933ddaae149.png">

Also, as a result, horizontal scroll appears.

**Comment by straker** [comment]
Interesting. I can't see this same behavior on my end. Do you have an example site I could look at to see what might be causing it?

**Comment by Kamilius** [comment]
@straker hi, sadly - no. It's local page. It appeared from a very beginning, when I just installed `livingcss` and provided comments for first `button` element.
Fixed this by overriding `min-width` with following:
```css
body.livingcss-example {
  min-width: auto;
}
```

**Comment by Kamilius** [comment]
Closing because workaround found and also lacking of a public page to demonstrate a bug.
