### ISSUE TITLE
Order dependence in @section/@sectionof declarations

### ISSUE THREAD

**Issue by sidraval** [straker/livingcss#30]
Hello,

Currently if a doc comment with, e.g. `@section A` gets parsed before a doc comment with, e.g. `@sectionof A` the styleguide will fail with `ReferenceError: section 'A' is not defined`. Would it be possible to implement a parsing scheme such as:

* Documentation with a single `@section` gets parsed before documentation with any `@sectionof`
* Documentation with a single `@sectionof` gets parsed before documentation with 2+ `@sectionof`
* etc...

I haven't thought this through 100% but it seems like a nice improvement (and would help my use case 😄 ).

**Comment by straker** [comment]
Could you provide an example of comment ordering that causes the problem? From what I understood, this is the ordering you described:

```
/**
 * Section A
 * @section A
 */

/**
 * Section B
 * @sectionof B
 */
```

**Comment by Kamilius** [comment]
@straker I think that's almost the case you've provided. He means, that both of those comments are in different files, and `@sectionof A` document getting parsed prior to `@section A` which causes this error.

@sidraval I've solved it in a following way:
I have a case, when main `@section` is defined inside `input.scss` and `alert.scss`, `validation.scss` are a subsections of this section:
`generate.js` file:
```js
...
livingcss([
  // 'input.scss', 'alert.scss', 'validation.scss' should be parsed only in a given order,
  // as they are using same styleguide @section which is defined inside 'input.scss'
  `${dirName}/styles/input.scss`,
  `${dirName}/styles/alert.scss`,
  `${dirName}/styles/validation.scss`,
  `${dirName}/styles/**/!(alert|input|validation).scss`, // parse rest of files, which are not alert/input/validation
], `${dirName}/styleguide`, options);
```

**Comment by straker** [comment]
@Kamilius's solution is probably the easiest. If you need to parse your sections in a specific order but display them in a different order, you can use the `sortOrder` option to put them back in the desired order.

Using Kamilius's example:

```
let options = {
  sortOrder: [
    // sort alerts, then inputs, then validations
    ['alert', 'input', 'validation']
  ]
};
```

**Comment by sidraval** [comment]
@straker @Kamilius Thanks for the responses! The workaround fits my needs.

I am also interested in not having to maintain the ordering anywhere, hence the suggestion about processing certain doc comments before others. But if that is of limited benefit (or perhaps has an issue I haven't thought about), no worries 👍 

Feel free to close at your discretion.

**Comment by straker** [comment]
After some thought, I decided to implement this feature so you don't have to order your src files in parse order. The display order will still be determined by parse order of the sections and subsections, so you'll still need to use `sortOrder` to adjust that.

**Comment by airtonix** [comment]
For dudes how have far more complex file structures, I suggest you do the following:

1. control the import of your child sections in `_index.scss` files: 

```
src/core/
  _index.scss

  settings/
    _index.scss
    mixins/
      _mediaquery.scss
    functions/
      _colours.scss
    config/
      _z-index.scss
      _colours.scss
      _breakpoints.scss
      _type.scss

  components/
    _index.scss
    buttons/
      _buttons.scss
      _buttons--largeup.scss
      _icon-buttons.scss
    site-header/
      _navigation.scss
      _navigation--largeup.scss
      _navigation--xlargeup.scss
      _logo.scss
      _mega-menu.scss
    site/
      _layout.scss
```

2. use your `_index.scss` files to include the contents of the folder

```

/**
 * @section buttons
 * @sectionof core.components
 */

```

3. in your components, control your breakpoints: 

```
/**
 * @section components
 * @sectionof core
 */

@import './buttons/buttons';
@import './buttons/icon-buttons';

@include mq(largeup) {
  @import './buttons/buttons--largeup';
  @import './buttons/navigation--largeup';
}

@include mq(xlargeup) {
  @import './buttons/navigation--xlargeup';
}

4. in your `src/core/_index.scss`

```
/**
 * @section core
 */
```

Now with that structure, process all your `_index` first, then the children.

```
livingcss([
  './src/**/_index.scss',
  './src/**/!(_index).scss'
], './styleguide'. {});
```

This ensures all your parent level components are sorted.
