### ISSUE TITLE
sortOrder for child sections

### ISSUE THREAD

**Issue by Kamilius** [straker/livingcss#33]
How to set a sort order for a child sections of a given section? For page, it is obvious from a doc:
```js
options = {
  sortOrder: [
    {
      index: [
        '1. Section A',
        '2. Section B',
      ],
    },
  ],
};
```

What if I have a few sub-sections: `'2.2 Section C'` and `'2.1 Section Z'`, for `'2. Section B'`. How to sort them?

**Comment by straker** [comment]
Sorry for the late response, I was at a conference all week.

I don't believe sorting sub-sections is currently possible other than through making sure they are in the proper order during parsing.

**Comment by Kamilius** [comment]
@straker, ok thanks for now.
