### ISSUE TITLE
Will not process preserved comments

### ISSUE THREAD

**Issue by phun-ky** [straker/livingcss#34]
I'm creating a living styleguide from many stylus files, and each file is documented with JSDoc syntax (I am currently converting from documentcss). The files are preprocessed and bundled into a bundle file containing all relevant documentation. To actually preserve the comments through the preprocessor, I am forced to use exclamation marks to dictate which comments the preprocessor shall not remove. This results in livingcss not handling the JSDoc. Why?

To clarify, this works with livingcss:

    /**
     * My Section
     *
     * A description of the section and how to use it.
     *
     * @section
     */

This does not:

    /**!
     * My Section
     *
     * A description of the section and how to use it.
     *
     * @section
     */

How can I make use of this module without removing the exclamation mark?

**Comment by phun-ky** [comment]
Is this something that I've to take up with https://github.com/yavorskiy/comment-parser ?

**Comment by straker** [comment]
Ya, the comment parsing is done through comment-parser so you'd have to take it up with them. 

You could also pass livingcss the stylus files unpreprocessed so the comments wouldn't have the `!`.

**Comment by phun-ky** [comment]
> You could also pass livingcss the stylus files unpreprocessed so the comments wouldn't have the !.

I think you are missing the point. For the stylus preprocessor to keep the comments, I have to include the exclamation mark `!`

Will try to use the raw files.

**Comment by phun-ky** [comment]
Closing this, since using the raw files directly is working for me
