### ISSUE TITLE
LivingCSS in IE11

### ISSUE THREAD

**Issue by kriss145** [straker/livingcss#39]
Hi,

Livingcss works in the IE11? I asking you beacuse I'm testing now and CSS is not loaded.

Thanks

PS. Could you update gulp-livingcss with the latest livingcss? :)

**Comment by straker** [comment]
Fixed in v4.2.3

**Comment by kriss145** [comment]
Hi,

I used latest gulp-livingcss (he has still livingcss v4.0.0) but I updated livingcss package to v4.2.3
This still dosen't work.

<img width="976" alt="screen" src="https://cloud.githubusercontent.com/assets/3781356/25324806/234e1112-28c8-11e7-8577-d377fd3f4f7c.png">

**Comment by straker** [comment]
Hu, https://straker.github.io/livingcss/ looks like its working in ie11. Are you using a custom template (the 'show code' button is not part of the default template)?

Also, gulp-livingcss is pinned to `^4.0.0` of livingcss, which means you should get the latest 4.x release (in this case 4.2.3). I'm not sure why you wouldn't be on installing gulp-livingcss.

**Comment by kriss145** [comment]
Hmm, on your example works. Unfortunately I have still problem in my template.

Do you changed something else besides urls to JS scripts?

**Comment by straker** [comment]
For the default template, I just [updated the webcomponentjs file](https://github.com/straker/livingcss/commit/4bf798c8e9ce094dd07b82a751dfc89b5d31efd1) to use the version that supports shadow dom
