### ISSUE TITLE
Demo please

### ISSUE THREAD

**Issue by MartinMuzatko** [straker/livingcss#4]
this sounds promising, is there a demo to see a styleguide in action?

**Comment by straker** [comment]
There are some demos inside the examples directory of this repo. The [FamilySearch.org Style Guide](https://familysearch.org/reference/styleguide/) is also using it with a custom Handlebars template. It's parsing the comments from [this repo](https://github.com/fs-webdev/fs-styles).

**Comment by MartinMuzatko** [comment]
Ah! The FamilySearch.org Styleguide helped me to see what this tool is doing. thank you very much!

**Comment by reintroducing** [comment]
This is fantastic work. I do agree, however, that you'd probably want to make the demo (in this case the FamilySearch.org SG) more prominent in the readme, and by that I mean add it at the top.  One of the first things I do when I look at these types of tools is go see a demo and see if it even looks remotely close to what I'm after.  By not putting that link in the readme I think you're possibly losing a lot of people that don't want to read a long page of documentation without knowing what it will actually output.

**Comment by straker** [comment]
Good point. I'll add it to the repo and probably also create a github page that shows off the default template.

**Comment by straker** [comment]
Readme has been updated with two demos.

**Comment by reintroducing** [comment]
Awesome, I think that's extremely helpful!
