### ISSUE TITLE
Images are not loaded

### ISSUE THREAD

**Issue by kriss145** [straker/livingcss#40]
Hi,

I have a one more question

How we can change path to images in the styleguide?
The only way is to use ex. "/path"?

Thanks!

**Comment by straker** [comment]
I'm not sure I understand the question. LivingCSS doesn't have any images, so are you referring to images in your own stylesheets? Could you provide an example of what you mean?

**Comment by kriss145** [comment]
Hi,

I'm using relative path to images in my CSS.
My images are in path "project/tpl/img" and CSS path "project/tpl/css"
Catalog "styleguide" is generated in path "project/"
I'm using now path ex. "../img/file.png"

Now I found a different way. I moved "styleguide" to "tpl" catalog.

Anyway would be great to find solution for this :)
