### ISSUE TITLE
Access to FS custom Handlebar templates?

### ISSUE THREAD

**Issue by Fernker** [straker/livingcss#42]
Love this framework, been implementing it and love the flexibility of it.

I'm looking at making it a bit tighter as far as the HTML that is served up and I've noticed that in livingcss by default it inlines all the Polymer and included CSS files (including ours).  But when I go to the Family Search style guide (actual served pages) there is no Polymer on it.  Is there any chance of seeing those templates?  The linked GitHub for that seems to just be the actual files that create the CSS style guide and not the files that make the online style guide.

**Comment by straker** [comment]
I can share the template and the gulpfile from the FamilySearch style guide https://gist.github.com/straker/6cd9923fe1282452f094755fe4be8200

**Comment by Fernker** [comment]
Awesome thanks for that!

Just out of curiosity, why did FamilySearch decide not to use Polymer when this base app uses it?  (I'm trying to weigh the pros and cons of using Polymer for our style guide).

**Comment by straker** [comment]
The FS style guide has complete control over the layout, so it can use all the FS styles without clashing. I created both and I used Polymer in the generic output as it would guarantee that using Shadow DOM would prevent the user stylesheet from overriding global styles in the style guide, causing layout bugs.

**Comment by straker** [comment]
In terms of whether or not to use Polymer (or custom elements), I think there are great pros in that for a style guide. Take for example the complex code needed to use the [Person styles from the FS style guide](https://familysearch.org/frontier/styleguide/#persons). There is a lot of DOM elements that require specific ordering and classes. And it has a lot of variations that get even more complex.

Requiring devs to have to type that out each time means they have to look at the style guide every time they need to use it (which is a lot). If devs instead just had a single element they could use, the entire process becomes much easier. The devs don't have to worry about DOM order, class names, or even how to do all the variations they need. Instead they just use the custom element, have a simple attribute API to activate the variations, and done.

**Comment by Fernker** [comment]
Oh is FamilySearch using Polymer in the actual FamilySearch app?  I haven't looked at the source code there recently.  Or are you using some other framework variation of web components?
