### ISSUE TITLE
Looping Custom Tags?

### ISSUE THREAD

**Issue by brandonreid** [straker/livingcss#44]
I'm able to make a custom tag easy enough following the [documentation provided](https://github.com/straker/livingcss#custom-tags), but what I'd like to do when documenting colors, icons and other repeatable stuff, is create a custom tag that I can loop through in the template.

So ideally my styles file would look something like...
```
/**
* @section Color Palette
*
* @color {#F00} Brand Red ($brand-red) - Section Description
* @color {#F8F8F8} Foreground Shade ($fg-shade) - Used to shade foreground areas when needed.
**/
```

Then in a template I'd want to...
```
{{#each colors}}
  <p>{{color.name}}</p>
  etc...
{{/each}}
```

Is this possible?

Thanks in advance! Making my second pattern library with livingcss, such awesome stuff.

**Comment by straker** [comment]
Yep, multiple custom tags will be added as an array in the JSON context object.
