### ISSUE TITLE
Question: why define section at the end instead of before text?

### ISSUE THREAD

**Issue by gavinhewitt** [straker/livingcss#46]
Expecting to define an @section at the start of a comment section I was quite surprised that this is done at the very end. I was just curious what the reasoning behind this is. Personally I think it would make more sense to define it at the beginning, but maybe there's a good reason for it to do it differently. 

I'm talking about:

```
/**
 * This is the bodytext
 * 
 * @section Some section
 * /
```
vs
```
/**
 * @section Some section 
 * 
 * This is the bodytext
 * /
```

Awesome library btw!!

**Comment by straker** [comment]
No reason, was just how I saw other comment parsing libraries do it (such as KSS).
