### ISSUE TITLE
Upgrade to Gulp 4

### ISSUE THREAD

**Issue by sprynm** [straker/livingcss#52]
Looking to see if you are actively upgrading this to Gulp 4.  The current package versions throw warnings and have a few issues that an upgrade fixed.  If not, perhaps I can help as it only took a few changes on my local to get things running again.

**Comment by straker** [comment]
I haven't been working on upgrading to gulp 4. If you want to submit a pr to do so that would be fantastic.

**Comment by straker** [comment]
Closed with #53
