### ISSUE TITLE
Description losing markdown 

### ISSUE THREAD

**Issue by sprynm** [straker/livingcss#60]
Hi again.

I'm looking to normalize my comments by explicitly naming sections:
```
* @section My Section
* @sectionof My Other Section
* @description 
* Some `markdown` code for a description
```
However this is breaking the markdown parsing for some reason.

I get these outcomes from the following.

## EG1
```
* My Section
* Some `markdown` code for a description
* @sectionof My Other Section
```
Markdown parsed
## EG2
```
* @section My Section
* @sectionof My Other Section
* Some `markdown` code for a description
```
Description is plain text and requires HTML tags.

## EG3
```
* @section My Section
* @sectionof My Other Section
* @description Some `markdown` code for a description
```
Same as above regardless of the line @description 

## EG4
```
* @section My Section
* @sectionof My Other Section
* @description {markdown} Some `markdown` code for a description
```
Description is replaced with `[object Object]`

## EG5
```
* Some `markdown` code for a description
* @section My Section
* @sectionof My Other Section
```
Markdown parsed but awkward as the section name is buried a bit in the comment.

## EG6
```
* My Section
* Some `markdown` code for a description
* @section My Section
* @sectionof My Other Section
```
Markdown parsed but title is inferred and duplicated

What do you think is my best path here?

**Comment by straker** [comment]
So the comment parser only parses text before any tags. Any text after tags will be skipped by the parser.

* EG 1 - My preferred method. I like to also put a blank line between the heading, description, and tags just [for styling purposes](https://github.com/fs-webdev/fs-styles/blob/master/assets/css/elements/_buttons.styl#L50-L106).

```js
/** 
 * My Section
 *
 * Some `markdown` code for a description
 *
 * @sectionof My Other Section
 */
```

* Eg 2 - This shouldn't work as tags can be multiple lines. The parser should treat all that as the name for the `@sectionof` tag (so `My Other Section\nSome `markdown` code for a description`)
* EG 3 - `@description` is being treated as a custom tag and will be parsed as plain text
* EG 4 - Also a custom tag, but with the addition of the `type`, an object is created for the tag description of: 

```js
{
  description: "<p>Some <code>markdown</code> code for a description</p>",
  type: "markdown"
}
```

* EG 5 - Works, and is fine if you'd prefer a sections name was always obvious and not inferred
* EG 6 - Works, but the duplication is odd. Would use EG 5 over this one.

**Comment by sprynm** [comment]
I see. So for EG4, I need to push the tag.description.description up a level? Might that be something that Livingcss could do when type is markdown?

**Comment by sprynm** [comment]
For now, I added this to my custom tags:
```
var marked = require('marked');
var trailingNewline = /\s+$/;
...
preprocess: function (context, template, Handlebars) {
  tags: {
    description: function () {
      if (this.tag.type == "markdown"){
        this.block.description = "LANCE TEST2: " + marked(unescape(this.tag.description)).replace(trailingNewline, '');
      }
    }
  }
}
```

Curious if there is any harm in "marking"  all descriptions or should I be explicit?   For see any problems?

**Comment by straker** [comment]
Markdown is already a special tag type, so I could probably make it so any tag with only a type of `{markdown}` and no name would just convert it into a DOM string.

As for your custom tag, you only mark the description if it is also of type markdown, so it should be safe. Only problem I can foresee is if someone were to use the description tag without adding the markdown type, no output would be given (might be unexpected).

**Comment by sprynm** [comment]
it got pretty repetitive adding the type then getting blanks if I forgot one so I just opened the taps. So far, I can't see any downsides.
